//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.23 at 04:53:00 PM EEST 
//


package org.msh.quantb.model.forecast;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.msh.quantb.model.gen.Medicine;


/**
 * Medicine parameters and result of forecasting
 * 			
 * 
 * <p>Java class for ForecastingMedicine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ForecastingMedicine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="medicine" type="{http://www.msh.org/quantb/model/gen}Medicine"/>
 *         &lt;element name="stockOnOrderLT" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="consumptionLT" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="quantityMissingLT" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="quantityExpiredLT" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="consumptionCases" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="consumptionNewCases" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="unitPrice" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="stockOnHand" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="batchesToExpire" type="{http://www.msh.org/quantb/model/forecast}ForecastingBatch" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="orders" type="{http://www.msh.org/quantb/model/forecast}ForecastingOrder" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="results" type="{http://www.msh.org/quantb/model/forecast}ForecastingResult" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="packOrder" type="{http://www.msh.org/quantb/model/forecast}PricePack" minOccurs="0"/>
 *         &lt;element name="ajustmentEnrolled" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="adjustmentExpected" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ForecastingMedicine", propOrder = {
    "medicine",
    "stockOnOrderLT",
    "consumptionLT",
    "quantityMissingLT",
    "quantityExpiredLT",
    "consumptionCases",
    "consumptionNewCases",
    "unitPrice",
    "stockOnHand",
    "batchesToExpire",
    "orders",
    "results",
    "packOrder",
    "ajustmentEnrolled",
    "adjustmentExpected"
})
public class ForecastingMedicine {

    @XmlElement(required = true)
    protected Medicine medicine;
    protected int stockOnOrderLT;
    protected int consumptionLT;
    protected int quantityMissingLT;
    protected int quantityExpiredLT;
    protected int consumptionCases;
    protected int consumptionNewCases;
    protected int unitPrice;
    protected int stockOnHand;
    protected List<ForecastingBatch> batchesToExpire;
    protected List<ForecastingOrder> orders;
    protected List<ForecastingResult> results;
    protected PricePack packOrder;
    @XmlElement(required = true)
    protected BigDecimal ajustmentEnrolled;
    @XmlElement(required = true)
    protected BigDecimal adjustmentExpected;

    /**
     * Gets the value of the medicine property.
     * 
     * @return
     *     possible object is
     *     {@link Medicine }
     *     
     */
    public Medicine getMedicine() {
        return medicine;
    }

    /**
     * Sets the value of the medicine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Medicine }
     *     
     */
    public void setMedicine(Medicine value) {
        this.medicine = value;
    }

    /**
     * Gets the value of the stockOnOrderLT property.
     * 
     */
    public int getStockOnOrderLT() {
        return stockOnOrderLT;
    }

    /**
     * Sets the value of the stockOnOrderLT property.
     * 
     */
    public void setStockOnOrderLT(int value) {
        this.stockOnOrderLT = value;
    }

    /**
     * Gets the value of the consumptionLT property.
     * 
     */
    public int getConsumptionLT() {
        return consumptionLT;
    }

    /**
     * Sets the value of the consumptionLT property.
     * 
     */
    public void setConsumptionLT(int value) {
        this.consumptionLT = value;
    }

    /**
     * Gets the value of the quantityMissingLT property.
     * 
     */
    public int getQuantityMissingLT() {
        return quantityMissingLT;
    }

    /**
     * Sets the value of the quantityMissingLT property.
     * 
     */
    public void setQuantityMissingLT(int value) {
        this.quantityMissingLT = value;
    }

    /**
     * Gets the value of the quantityExpiredLT property.
     * 
     */
    public int getQuantityExpiredLT() {
        return quantityExpiredLT;
    }

    /**
     * Sets the value of the quantityExpiredLT property.
     * 
     */
    public void setQuantityExpiredLT(int value) {
        this.quantityExpiredLT = value;
    }

    /**
     * Gets the value of the consumptionCases property.
     * 
     */
    public int getConsumptionCases() {
        return consumptionCases;
    }

    /**
     * Sets the value of the consumptionCases property.
     * 
     */
    public void setConsumptionCases(int value) {
        this.consumptionCases = value;
    }

    /**
     * Gets the value of the consumptionNewCases property.
     * 
     */
    public int getConsumptionNewCases() {
        return consumptionNewCases;
    }

    /**
     * Sets the value of the consumptionNewCases property.
     * 
     */
    public void setConsumptionNewCases(int value) {
        this.consumptionNewCases = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     */
    public int getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     */
    public void setUnitPrice(int value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the stockOnHand property.
     * 
     */
    public int getStockOnHand() {
        return stockOnHand;
    }

    /**
     * Sets the value of the stockOnHand property.
     * 
     */
    public void setStockOnHand(int value) {
        this.stockOnHand = value;
    }

    /**
     * Gets the value of the batchesToExpire property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the batchesToExpire property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBatchesToExpire().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForecastingBatch }
     * 
     * 
     */
    public List<ForecastingBatch> getBatchesToExpire() {
        if (batchesToExpire == null) {
            batchesToExpire = new ArrayList<ForecastingBatch>();
        }
        return this.batchesToExpire;
    }

    /**
     * Gets the value of the orders property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orders property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForecastingOrder }
     * 
     * 
     */
    public List<ForecastingOrder> getOrders() {
        if (orders == null) {
            orders = new ArrayList<ForecastingOrder>();
        }
        return this.orders;
    }

    /**
     * Gets the value of the results property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the results property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResults().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForecastingResult }
     * 
     * 
     */
    public List<ForecastingResult> getResults() {
        if (results == null) {
            results = new ArrayList<ForecastingResult>();
        }
        return this.results;
    }

    /**
     * Gets the value of the packOrder property.
     * 
     * @return
     *     possible object is
     *     {@link PricePack }
     *     
     */
    public PricePack getPackOrder() {
        return packOrder;
    }

    /**
     * Sets the value of the packOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link PricePack }
     *     
     */
    public void setPackOrder(PricePack value) {
        this.packOrder = value;
    }

    /**
     * Gets the value of the ajustmentEnrolled property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAjustmentEnrolled() {
        return ajustmentEnrolled;
    }

    /**
     * Sets the value of the ajustmentEnrolled property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAjustmentEnrolled(BigDecimal value) {
        this.ajustmentEnrolled = value;
    }

    /**
     * Gets the value of the adjustmentExpected property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAdjustmentExpected() {
        return adjustmentExpected;
    }

    /**
     * Sets the value of the adjustmentExpected property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAdjustmentExpected(BigDecimal value) {
        this.adjustmentExpected = value;
    }

}
