//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.23 at 04:53:00 PM EEST 
//


package org.msh.quantb.model.regimen;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.msh.quantb.model.regimen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Regimens_QNAME = new QName("http://www.msh.org/quantb/model/regimen", "regimens");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.msh.quantb.model.regimen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Regimens }
     * 
     */
    public Regimens createRegimens() {
        return new Regimens();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Regimens }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.msh.org/quantb/model/regimen", name = "regimens")
    public JAXBElement<Regimens> createRegimens(Regimens value) {
        return new JAXBElement<Regimens>(_Regimens_QNAME, Regimens.class, null, value);
    }

}
