//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.23 at 04:53:00 PM EEST 
//


package org.msh.quantb.model.medicine;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.msh.quantb.model.gen.Medicine;
import org.msh.quantb.model.gen.SimpleStamp;


/**
 * <p>Java class for Medicines complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Medicines">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="medicines" type="{http://www.msh.org/quantb/model/gen}Medicine" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="stamp" type="{http://www.msh.org/quantb/model/gen}SimpleStamp"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Medicines", propOrder = {
    "medicines",
    "stamp"
})
public class Medicines {

    protected List<Medicine> medicines;
    @XmlElement(required = true)
    protected SimpleStamp stamp;

    /**
     * Gets the value of the medicines property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicines property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicines().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Medicine }
     * 
     * 
     */
    public List<Medicine> getMedicines() {
        if (medicines == null) {
            medicines = new ArrayList<Medicine>();
        }
        return this.medicines;
    }

    /**
     * Gets the value of the stamp property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleStamp }
     *     
     */
    public SimpleStamp getStamp() {
        return stamp;
    }

    /**
     * Sets the value of the stamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleStamp }
     *     
     */
    public void setStamp(SimpleStamp value) {
        this.stamp = value;
    }

}
