//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.23 at 04:53:00 PM EEST 
//


package org.msh.quantb.model.errorlog;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.msh.quantb.model.errorlog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ErrorLog_QNAME = new QName("http://www.msh.org/quantb/model/errorlog", "ErrorLog");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.msh.quantb.model.errorlog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ErrorLog }
     * 
     */
    public ErrorLog createErrorLog() {
        return new ErrorLog();
    }

    /**
     * Create an instance of {@link LogRecord }
     * 
     */
    public LogRecord createLogRecord() {
        return new LogRecord();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorLog }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.msh.org/quantb/model/errorlog", name = "ErrorLog")
    public JAXBElement<ErrorLog> createErrorLog(ErrorLog value) {
        return new JAXBElement<ErrorLog>(_ErrorLog_QNAME, ErrorLog.class, null, value);
    }

}
