//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.23 at 04:53:00 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.msh.org/quantb/model/errorlog")
package org.msh.quantb.model.errorlog;
